version: "3"
services:
  simpleapp.demo.wbitt.com:
    build: .
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:simpleapp.demo.wbitt.com
    volumes:
      - ${PWD}/site.conf:/config/site.conf

    env_file:
    - simpleapp.env

    networks:
      - services-network

networks:
  services-network:
    external: true

